tasks:
  - name: Start Logto
    init: |
      curl -fsSL https://raw.githubusercontent.com/logto-io/logto/f9e46de8ca021b91ff50cbdced0ba26d8224f0b3/docker-compose.yml > docker-compose.yml
      docker compose pull
    command: |
      ENDPOINT=$(gp url 3001) docker compose -p logto up
    env:
      TAG: prerelease
ports:
  - name: Logto
    description: The Logto core service
    port: 3001
    visibility: public
